/*
-- Query: SELECT * FROM django_db.dapp_batch
LIMIT 0, 1000

-- Date: 2025-03-28 07:20
*/
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (1,'YG-R-01','8:00am to 9:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (2,'YG-R-02','4.30pm to 5.30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (3,'YG-R-03','5.45pm to 6.15pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (4,'YG-R-04','4.30pm to 5.30pm / 8.00 am to 9.00 am ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (5,'YG-WR-01','8:00am to 9:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (6,'YG-W-01','9.15am to 10.15am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (7,'YG-PT',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (8,'SQ-WR-01','Thu(4:30pm to 5:30) Sat/Sun(8:00am to 9:00am)');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (9,'SQ-R-02','4.30pm to 5.30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (10,'SQ-R-03','4.30pm to 5.30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (11,'SQ-I-01','Tue/Thu(5:30pm to 6:30pm) Sat/Sun(8:00 to 9:00am)');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (12,'SQ-IA-01','\"Tue/Wed/Fri- 6.00 am to 8.00 am and  Sat/Sun - 9.00 am to 11.00 am \nTue/Fri - 6 am - 7 am (S &C )\"');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (13,'SQ-W-01','8:00am to 9:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (14,'SQ-I-02','9.00am to 11.00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (15,'SQ-W-AD','7:00am to 8:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (16,'SQ-PT',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (17,'SQ-TISB','\"Tue/Wed/Thur/Fri - 3 pm to 4:30 pm\nSat/Sun - 8:00 am to 9 am\"');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (18,'SQ-INV','3 pm to 4 pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (19,'BD-R-02','4.30pm to 6.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (20,'BD-R-03','4.30pm to 6.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (21,'BD-R-04','4.30pm to 6.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (22,'BD-IA-01','5.30pm to 7.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (23,'BD-IA-02','5.30pm to 7.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (24,'BD-W-01','8:00am to 9:30am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (25,'BD-W-02','9.30am to 11.00am ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (26,'BD-RW-01','Friday - 4.30pm to 6.00pm & Weekend - 8.00 am to 9.30 am ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (27,'BD-W-AD',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (28,'BD-PT',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (29,'BD-10X-Tue','9.00 am to 9.45 am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (30,'BD-10X-THU','9.00 am to 9.45 am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (31,'BD-INV','3.00 pm to 4.00 pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (32,'TT-R-02','4.45pm to 5.45pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (33,'TT-IA-01','\"(R) 6.00pm to 7.30pm & (W) 9.00am to 10.30am\nS & C - Tuesday & Thursday - 6 pm to 7.30pm\"');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (34,'TT-W-01','8:00am to 9:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (35,'TT-IA-W1','9.00am to 10.30am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (36,'TT-W-Ad','11 am - 12.00 pm ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (37,'TT-PT','1 Hour');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (38,'TT-TISB','7:30 am to 9 am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (39,'CS-R-02','6.00pm to 7.00pm ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (40,'CS-W-01','8:00am to 9:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (41,'CS-W-02','Sat/Sun :9.00am to 10.00am, Online on Wed - 7.00pm to 8.00 pm ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (42,'CS-W-03','11:30am to 12:30pm, Online on Wed - 7.00pm to 8.00 pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (43,'CS-IA-01','Sat / Sun: 10 am to 11.30 am , Online on Tue / Thu: 8.00 pm to 9.30 pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (44,'CS-PT',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (45,'FB-R-01','4.30pm to 5.30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (46,'FB-R-02','\"T/Th/Fri - 5.30pm to 7.00pm \nWed - 5.15pm to 6.45 pm \n\nS&C - Wed (515-615pm) & Fri (5.30-6.30pm)\"');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (47,'FB-W-01','8:30am to 9:30am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (48,'FB-W-02','9.30am to 10.30am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (49,'FB-W-03','10.45am to 11.45am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (50,'FB-W-04','10.45am to 11.45am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (51,'FB-PT',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (52,'BB-R-01','5.30pm to 7.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (53,'BB-R-02','4.15pm to 5.30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (54,'BB-RW-03','5.30pm to 7.00pm (Weekday) and 9.00am to 10.00am (Weekend)');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (55,'BB-WR-01','4.15pm to 5.30pm (Weekday) and 8.00am to 9.00am (Weekend)');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (56,'BB-WR-02','\"MTWF - 5.30 pm to 7.00 pm\nSS - 10.00 am to 11.00 am\nWednesday & Saturday - SnC (1 hour)\"');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (57,'BB-IA-01','8:00am to 9:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (58,'BB-W-01','8:00am to 9:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (59,'BB-W-02','9:00am to 10:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (60,'BB-W-I-01','10:00am to 11:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (61,'BB-PT',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (62,'BB-10X-Thu','9 am to 9:45 am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (63,'GYS-R-01','4.30pm to 5.30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (64,'GYS-R-02','5:30pm to 6:30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (65,'GYS-R-04','4:30pm to 5:30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (66,'GYS-R-03','5.30pm to 6.30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (67,'GYS-R-PSJ','5.30pm to 6.30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (68,'GYS-R-PSJ-01','5.30pm to 6.30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (69,'GYS-R-PSJ-02','Tue/Thu-5:30 to 6:30pm & Sun- 8:00 to 9:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (70,'GYS-R-PSJ-03','Wed-5:30 to 6:30pm & Sat/Sun- 8:00 to 9:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (71,'GYS-I-01','4:00pm to 6:00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (72,'GYS-A-01','Tue/Wed/Thu - 5:30am to 8:00am & Sat/Sun - 8:00am to 12:00 pm (other option if ma\'am allows Tue/Thu 5:30 am)');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (73,'GYS-W-01','8:00am to 9:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (74,'GYS-W-02','9:00am to 10:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (75,'GYS-W-03','10:00am to 11:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (76,'GYS-I-W1','8:00am to 12:00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (77,'GYS-I-W2','2hrs');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (78,'GYS-PT',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (79,'GYS-TISB','7:30 am to 9 am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (80,'GYS-INV','3 pm to 4 pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (81,'SH-FCR-01','1 Hour - 9am-12pm & 3pm-6pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (82,'SH-FC-02','5.00pm to 6.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (83,'SH-R-01','1hrs');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (84,'SH-IA-01','1.5hours');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (85,'SH-W-01','9.30am to 10.30am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (86,'SH-FC-00','8 hours - 8.00am -11.00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (87,'SH-TISB1','8.00am to 9.00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (88,'SH-TISB2','9.00am to 10.00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (89,'SH-DPSEH (M)','9.00am to 10.00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (90,'SH-DPSEH (F)','9.00am to 10.00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (91,'SH-DPSESB','9.00am to 10.00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (92,'GYM-M','');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (93,'GYM-Q',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (94,'GYM-SA',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (95,'GYM-AN',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (96,'GYM-A',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (97,'GYM-M-E',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (98,'GYM-Q-E',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (99,'GYM-SA-E',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (100,'GYM-AN-E',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (101,'GYM-GC','\" 6 am to 7 am \r');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (102,'GYM-PT','');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (103,'LTAD-2D','6pm-7pm ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (104,'BX-GC-01','\"5.30 pm to 6.30 pm (Tuesday & Thursday)');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (105,'BX-GC-02','\"6.00 pm to 7.00 pm \n');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (106,'BX-PT',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (107,'ATH-R-01','4.30pm to 6.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (108,'ATH-R-03','3:00pm to 4:30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (109,'ATH-W-01','8:00am to 9:30am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (110,'ATH-PT','1 hour session');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (111,'SW-R-01','6.30am to 7.15am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (112,'SW-R-02','7:15am to 8:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (113,'SW-R-03','8:00am to 8:45am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (114,'SW-R-04','6.30am to 7.15am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (115,'SW-R-05','5:15pm to 6:00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (116,'SW-R-06','6.00pm to 6.45pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (117,'SW-R-07','6.00pm to 6.45pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (118,'SW-R-08','4:30pm to 5:15pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (119,'SW-R-09','6.45pm to 7:30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (120,'SW-R-10','7:15am to 8:00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (121,'SW-R-11','9:00 am to 9:45 am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (122,'SW-10X-Tue','9:00 am to 9:45 am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (123,'SW-10X-Thu','9:00 am to 9:45 am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (124,'SW-W-01','8.45am to 9.30am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (125,'SW-W-02','10.15am to 11.00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (126,'SW-W-03','5.15pm to 6.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (127,'SW-W-04','8.00am to 8.45am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (128,'SW-W-05','9.30am to 10.15pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (129,'SW-W-06','6:00pm to 6:45pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (130,'SW-W-07','4.30pm to 5.15pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (131,'SW-W-08','11.00am to 11.45am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (132,'SW-W-10','6:30 am to 7:15 am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (133,'SW-W-11','7:15 am to 8 am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (134,'SW-T-01','5.20am to 6.30am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (135,'SW-SC-01','6.30am to 8.00am');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (136,'SW-RPC-01','5.00pm to 6.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (137,'SW-RPC-02','4.00pm to 5.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (138,'SW-WPC-01','4.00pm to 5.00pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (139,'SW-C-01','\"Monday, Tuesday, Wednesday & Friday - 6pm to 8pm\nSaturday - 6am- 8am \n\nSunday - Off \n\nS & C - Tuesday and Thursday - 5 pm \"');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (140,'SW-CS-02','Monday to Saturday - 6pm-8pm ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (141,'SW-HP-F','\"Mon/Wed/Fri - 8 am to 10 am\nMon/Wed/Fri - 3 pm to 5 pm\nTue/Thur - 6 pm to 8 pm\nSat - 8 am to 10 am\"');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (142,'SW-PT','\"Weekday - Rs.1800/ Session\nWeekend - Rs. 3000/ Session\n\nSpecial Child - Rs. 2000/ Session\"');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (143,'SWBF-BF','10:15 am - 10:45 am ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (144,'SWBF-JF','10:45 am - 11:15 am ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (145,'SWBF-SF','11:15 am - 12:00 pm ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (146,'SW-LS-3D',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (147,'SW-LS-2D',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (148,'SW-LSW-2D',NULL);
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (149,'SW-W-09','3.45pm to 4.30pm');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (150,'SW-CS-03','\"Monday to Saturday - 6pm-8pm \r Wednesday & Friday - 5am to 630am\r Saturday - 6am- 8am \r  \r\r \r \r \r  \r Tuesday & Friday - 6 am \"');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (151,'SW-CS-04','Monday to Saturday - 6pm-8pm ');
INSERT INTO `` (`id`,`batch_id`,`activated_timings`) VALUES (152,'SW-GEAR','3:00 pm - 3:45 pm ');
